config/routes.rb
Rails.application.routes.draw do
  resources :outbound_webhooks do
    post 'delivery',  on: :collection
    post 'bounce',    on: :collection
    post 'opens',     on: :collection
    post 'click',     on: :collection
  end

  resources :outbound_messages

  root to: "home#index"
end

app/models/outbound_message.rb
class OutboundMessage < ApplicationRecord
  def self.import_message(msg_id)
    msg = OutboundMessage.where(message_id: msg_id).take

    unless msg
      message = MessageDetail.query_postmark_outbound_message_details(msg_id)

      begin
        outbound_message = OutboundMessage.new
        outbound_message.tag = message["Tag"] rescue ''
        outbound_message.message_id = message["MessageID"] rescue ''
        outbound_message.to = message["To"] rescue []
        outbound_message.cc = message["Cc"] rescue []
        outbound_message.bcc = message["Bcc"] rescue []
        outbound_message.recipients = message["Recipients"] rescue []
        outbound_message.received_at = message["ReceivedAt"] rescue nil
        outbound_message.from = message["From"] rescue ''
        outbound_message.subject = message["Subject"] rescue ''
        outbound_message.attachments = message["Attachments"] rescue []
        outbound_message.status = message["Status"] rescue ''
        outbound_message.track_opens = message["TrackOpens"] rescue nil
        outbound_message.track_links = message["TrackLinks"] rescue ''

        if outbound_message.save
          puts "Imported MessageID: #{outbound_message.message_id}"
          begin
            MessageDetail.import_message_detail(outbound_message.message_id)
            puts "Import Message Details using MessageID - #{outbound_message.message_id}"
          rescue Exception => e
            puts "#{e.message}: #{e.backtrace.inspect}"
            errors << "#{e.message}: #{outbound_message.message_id}"
            ErrorMailer.notify_sysadmin("Importing email message details from postmark has error: #{outbound_message.message_id}", e.message, e.backtrace, errors).deliver
          end
        end
      rescue Exception => e
        puts "#{e.message} \n\n #{e.backtrace.inspect}"
        ErrorMailer.notify_sysadmin('Importing outbound messages from postmark error', e.message, e.backtrace).deliver
      end
    end
  end

  def self.import_outbound_message(message)
    msg = OutboundMessage.where(message_id: message["MessageID"]).take

    unless msg
      begin
        outbound_message = OutboundMessage.new
        outbound_message.tag = message["Tag"] rescue ''
        outbound_message.message_id = message["MessageID"] rescue ''
        outbound_message.to = message["To"] rescue []
        outbound_message.cc = message["Cc"] rescue []
        outbound_message.bcc = message["Bcc"] rescue []
        outbound_message.recipients = message["Recipients"] rescue []
        outbound_message.received_at = message["ReceivedAt"] rescue nil
        outbound_message.from = message["From"] rescue ''
        outbound_message.subject = message["Subject"] rescue ''
        outbound_message.attachments = message["Attachments"] rescue []
        outbound_message.status = message["Status"] rescue ''
        outbound_message.track_opens = message["TrackOpens"] rescue nil
        outbound_message.track_links = message["TrackLinks"] rescue ''

        if outbound_message.save
          puts "Imported MessageID: #{outbound_message.message_id}"
          begin
            puts "Import Message Details using MessageID - #{outbound_message.message_id}"
            MessageDetail.import_outbound_message_detail(outbound_message.message_id)
          rescue Exception => e
            puts "#{e.message}: #{e.backtrace.inspect}"
            errors << "#{e.message}: #{outbound_message.message_id}"
            ErrorMailer.notify_sysadmin("Importing email message details from postmark has error: #{outbound_message.message_id}", e.message, e.backtrace, errors).deliver
          end
        end
      rescue Exception => e
        puts "#{e.message} \n\n #{e.backtrace.inspect}"
        ErrorMailer.notify_sysadmin('Importing outbound messages from postmark error', e.message, e.backtrace).deliver
      end
    end
  end

  # def message_recipients
  #   # From "{\"Email\"=>\"send2weiss@gmail.com\", \"Name\"=>\"\"}"
  #   # To ['' <send2weiss@gmail.com>, '' <send2weiss@gmail.com>]
  # end

  def self.query_postmark_outbound_messages(date_request, offset=0)
    return [] if date_request.blank?
    messages = `curl "https://api.postmarkapp.com/messages/outbound?count=500&offset=#{offset}&todate=#{date_request}&fromdate=#{date_request}" \
                -X GET -H "Accept: application/json" \
                -H "X-Postmark-Server-Token: #{ENV["POSTMARK_API_KEY"]}"`

    messages_to_json = self.parse_messages_to_json(messages)
  end

  def self.parse_messages_to_json(messages)
    return {} if messages.blank?
    parsed_messages = JSON.parse(messages)
  end

  # Curl Postmark API to get the 1st 500 records (Postmark has max 500 records per request)
  def self.get_totalcount_messages_days_ago(date_request)
    messages = query_postmark_outbound_messages(date_request)
    return messages["TotalCount"]
  end
end

app/controllers/outbound_messages_controller.rb
class OutboundMessagesController < ApplicationController
  before_action :authenticate

  def index
    @title= "Outbound Messages"
    @messages = OutboundMessage.paginate(:page => params[:page], :per_page => 30)
  end

  def show
    @title= "Outbound Message Details"
    @message = MessageDetail.where(message_id: params[:id]).take
  end
end

app/views/outbound_messages/index.html.erb
<div class="container">
  <h2><%= @title %></h2>
  <p>Here's the list of messages imported from Postmark</p>

  <div class="pages">
    <%= will_paginate @messages, class: 'found' %>
  </div>

  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Subject</th>
          <th style="width:13%">Tag</th>
          <th style="width:16%">Date &amp; Time</th>
        </tr>
      </thead>
      <tbody>
        <% if @messages.blank? %>
          <tr>
            <td> - </td>
            <td> - </td>
            <td> - </td>
          </tr>
        <% else %>
          <% @messages.each do |msg| %>
            <tr>
              <% unless msg.message_id.blank? %>
                <td>
                  <%= link_to "#{msg.try(:subject)}", outbound_message_path(id: msg.message_id) %><br />
                  <small>(MessageID: <%= msg.try(:message_id) %>)</small>
                </td>
              <% end %>
              <% unless msg.tag.blank? %><td><small><%= msg.try(:tag) %></small></td><% end %>
              <% unless msg.received_at.blank? %>
                <td><small><%= msg.received_at.strftime("%b %m, %l:%M:%S %p") %></small></td>
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/outbound_messages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', outbound_messages_path %>

<br /><br />

<p><small>SUBJECT</small>: <span><strong><%= @message.subject %></strong></span></p>

<p><small>FROM</strong></small>: <span><a href="mailto:<%= @message.from %>" target="_top"><%= @message.from %></a></span></p>

<p><small>TAG</strong></small>: <i><span><%= @message.tag %></i></span></p>

<p><small>OPEN TRACKING</strong></small>: <span><%= @message.open_tracking %></span></p>

<p><small>LINK TRACKING</strong></small>: <span><%= @message.link_tracking %></span></p>

<p><small>RECIPIENT(s)</strong></small>:</p>

<!-- <p><small>To</strong></small>:
  <span><%#= @message.normalize_to_recipient %></span>
</p>

<p><small>Cc</strong></small>: <span><%= @message.cc %></span></p> -->

<div style="width: 65%;">
  <% @message.message_events.each do |event| %>
    <% if ["Delivered", "Opened", "Clicked"].include?(event['Type']) %>
      <% if event['Type'].eql?("Delivered") %>
        <div>
          <ul style="list-style: none;">
            <li><small>Message <font color='green'><b><%= event['Type'] %></b></font> to <a href="mailto:<%= event["Recipient"] %>" target="_top"><%= event["Recipient"].downcase %></a> <br /></small></li>
            <li><small>Delivery message - <font color='grey'><%= event['Details']['DeliveryMessage'] %></font></small></li>
            <li><small>Destination server : <font color='maroon'><%= event['Details']['DestinationServer'] %></font></small></li>
            <li><small><font color='orange'><%= event['ReceivedAt'].to_datetime.strftime("%b %m, %l:%M %p") rescue '' %></font></small></li>
          </ul>
        </div>
      <% elsif event['Type'].eql?("Opened") %>
        <div>
          <ul style="list-style: none;">
            <li><small>Message <font color='blue'><b><%= event['Type'] %></b></font> by <a href="mailto:<%= event["Recipient"] %>" target="_top"><%= event["Recipient"].downcase %></a> <br /></small></li>
            <li>
              <div style="max-width: 50%">
                <small><font color='grey'><%= event['Details']['Summary'] %></font></small>
              </div>
            </li>
            <li><small><font color='orange'><%= event['ReceivedAt'].to_datetime.strftime("%b %m, %l:%M %p") rescue '' %></font></small></li>
          </ul>
        </div>
      <% elsif event['Type'].eql?("Clicked") %>
        <div>
          <ul style="list-style: none;">
            <li><small>Message <font color='blue'><b><%= event['Type'] %></b></font> by <a href="mailto:<%= event["Recipient"] %>" target="_top"><%= event["Recipient"].downcase %></a> <br /></small></li>
            <li>
              <div style="max-width: 50%">
                <small><font color='grey'><%= event['Details']['Summary'] %></font></small>
              </div>
            </li>
            <li><small><font color='orange'><%= event['ReceivedAt'].to_datetime.strftime("%b %m, %l:%M %p") rescue '' %></font></small></li>
          </ul>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

<!-- <p><small>MESSAGE</strong></small>:</p> -->
<!-- <li><small><%= event['ReceivedAt'].strftime("%b %m, %l:%M:%S %p") rescue '' %></small></li> -->
<iframe style="border: 1px dotted grey; width: 50vw;height: 73vh;position: relative; padding: 3px; bottom-border: 2px;" srcdoc="<%= @message.html_body %>" frameborder="0"></iframe>