config/routes.rb
Rails.application.routes.draw do
  resources :outbound_webhooks do
    post 'delivery',  on: :collection
    post 'bounce',    on: :collection
    post 'opens',     on: :collection
    post 'click',     on: :collection
  end

  resources :outbound_messages

  root to: "home#index"
end

app/views/layouts/_header.html.erb
<div class="masthead">
  <div class="logo">
    <%= link_to(image_tag("jobline_logo.png"), root_path, class: 'logo', alt: 'jobline')%>
  </div>
  <nav class="navbar navbar-expand-md navbar-light bg-light rounded mb-3">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse ">
      <ul class="navbar-nav text-md-center nav-justified w-100 primary">
        <li class="nav-item">
          <%= link_with_current("Home", root_path, /Home/, /index/) %>
        </li>
        <li class="nav-item">
          <%= link_with_current("Messages", outbound_messages_path, /OutboundMessage/, /index|show/) %>
        </li>
        <li class="nav-item">
          <%= link_with_current("Webhooks", outbound_webhooks_path, /OutboundWebhook/, /index|show/) %>
        </li>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Jobline Messages at Postmark"%></title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>

      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>

      <%= yield %>

      <footer class="footer">
        <p>&copy; Jobline 2017</p>
      </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  </body>
</html>